name: Publish Package to npmjs
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - name: Install Node.js
                uses: actions/setup-node@v3
                with:
                node-version: 18

            - uses: pnpm/action-setup@v2
                name: Install pnpm
                id: pnpm-install
                with:
                version: 7
                run_install: false
            - name: Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  pnpm install
                  cd packages/tug-ts
                  npm ci
                  npm run build $GITHUB_REF_NAME
                  npm run release
