name: Tests
on: [push]
jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - name: Install Node.js
                uses: actions/setup-node@v3
                with:
                node-version: 18

            - uses: pnpm/action-setup@v2
                name: Install pnpm
                id: pnpm-install
                with:
                version: 7
                run_install: false

            - name: Tests
              run: |
                  pnpm install
                  pnpm run ts
                  pnpm run build 0.0.0
                  cd packages/tug-ts
                  npm run static
                  npm run test -- --collectCoverage
